# Generated by Django 5.1.4 on 2025-01-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_cidades_usuario_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cidade',
            new_name='cidades',
        ),
    ]
